#version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  envoy:
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info" ]
    depends_on:
      - shipment-service
      - customer-service

  shipment-service:
    build: .
    command: [ "/app/shipment-service" ]
    environment:
      SERVICE_NAME: shipment-service
      DATABASE_URL: postgres://app:app@postgres:5432/app?sslmode=disable
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    depends_on:
      - postgres

  customer-service:
    build: .
    command: [ "/app/customer-service" ]
    environment:
      SERVICE_NAME: customer-service
      DATABASE_URL: postgres://app:app@postgres:5432/app?sslmode=disable
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    depends_on:
      - postgres

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol/config.yaml
    command: [ "--config=/etc/otelcol/config.yaml" ]

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"
